import type { Recipe } from '../types/recipe';

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Insalata di Quinoa e Verdure',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    summary: 'Un\'insalata fresca e nutriente con quinoa, pomodorini, cetrioli e olive.',
    readyInMinutes: 20,
    servings: 4,
    healthScore: 95,
    vegetarian: true,
    vegan: true,
    extendedIngredients: [
      { id: 1, name: 'Quinoa', amount: 200, unit: 'g', original: '200g Quinoa' },
      { id: 2, name: 'Pomodorini', amount: 200, unit: 'g', original: '200g Pomodorini' },
      { id: 3, name: 'Cetrioli', amount: 1, unit: 'pezzo', original: '1 Cetriolo' },
      { id: 4, name: 'Olive nere', amount: 50, unit: 'g', original: '50g Olive nere' },
    ],
    instructions: 'Cuoci la quinoa secondo le istruzioni sulla confezione.\nTaglia i pomodorini a metà.\nTaglia i cetrioli a cubetti.\nMescola tutti gli ingredienti in una ciotola.\nCondisci con olio d\'oliva e sale.',
  },
  {
    id: 2,
    title: 'Pasta con Pesto di Basilico',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500',
    summary: 'Pasta fresca con pesto fatto in casa, pomodorini e pinoli.',
    readyInMinutes: 15,
    servings: 2,
    healthScore: 85,
    vegetarian: true,
    extendedIngredients: [
      { id: 1, name: 'Pasta', amount: 300, unit: 'g', original: '300g Pasta' },
      { id: 2, name: 'Basilico', amount: 50, unit: 'g', original: '50g Basilico' },
      { id: 3, name: 'Pinoli', amount: 30, unit: 'g', original: '30g Pinoli' },
      { id: 4, name: 'Olio d\'oliva', amount: 50, unit: 'ml', original: '50ml Olio d\'oliva' },
    ],
    instructions: 'Cuoci la pasta in acqua bollente salata.\nPrepara il pesto frullando basilico, pinoli e olio.\nScola la pasta e condisci con il pesto.\nAggiungi pomodorini tagliati a metà.',
  },
  {
    id: 3,
    title: 'Risotto ai Funghi Porcini',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500',
    summary: 'Risotto cremoso con funghi porcini freschi e parmigiano.',
    readyInMinutes: 35,
    servings: 4,
    healthScore: 80,
    vegetarian: true,
    extendedIngredients: [
      { id: 1, name: 'Riso Arborio', amount: 400, unit: 'g', original: '400g Riso Arborio' },
      { id: 2, name: 'Funghi porcini', amount: 300, unit: 'g', original: '300g Funghi porcini' },
      { id: 3, name: 'Brodo vegetale', amount: 1, unit: 'litro', original: '1 litro Brodo vegetale' },
      { id: 4, name: 'Parmigiano', amount: 100, unit: 'g', original: '100g Parmigiano' },
    ],
    instructions: 'Trita i funghi e soffrigili in padella.\nAggiungi il riso e tostalo per qualche minuto.\nAggiungi il brodo caldo poco alla volta mescolando.\nQuando il riso è cotto, manteca con parmigiano.',
  },
  {
    id: 4,
    title: 'Bowl di Verdure e Legumi',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    summary: 'Bowl colorato con ceci, pomodorini, avocado e verdure fresche.',
    readyInMinutes: 25,
    servings: 2,
    healthScore: 90,
    vegetarian: true,
    vegan: true,
    extendedIngredients: [
      { id: 1, name: 'Ceci cotti', amount: 200, unit: 'g', original: '200g Ceci cotti' },
      { id: 2, name: 'Avocado', amount: 1, unit: 'pezzo', original: '1 Avocado' },
      { id: 3, name: 'Pomodorini', amount: 150, unit: 'g', original: '150g Pomodorini' },
      { id: 4, name: 'Rucola', amount: 50, unit: 'g', original: '50g Rucola' },
    ],
    instructions: 'Prepara i ceci cotti o usa quelli in scatola.\nTaglia l\'avocado a fette.\nTaglia i pomodorini a metà.\nDisponi tutto in una bowl con la rucola.\nCondisci con olio e limone.',
  },
  {
    id: 5,
    title: 'Curry di Verdure',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500',
    summary: 'Curry speziato con verdure miste, cocco e riso basmati.',
    readyInMinutes: 30,
    servings: 4,
    healthScore: 88,
    vegetarian: true,
    vegan: true,
    extendedIngredients: [
      { id: 1, name: 'Verdure miste', amount: 500, unit: 'g', original: '500g Verdure miste' },
      { id: 2, name: 'Latte di cocco', amount: 400, unit: 'ml', original: '400ml Latte di cocco' },
      { id: 3, name: 'Curry in polvere', amount: 2, unit: 'cucchiai', original: '2 cucchiai Curry' },
      { id: 4, name: 'Riso basmati', amount: 300, unit: 'g', original: '300g Riso basmati' },
    ],
    instructions: 'Taglia le verdure a pezzi.\nSoffriggi le verdure con il curry.\nAggiungi il latte di cocco e lascia cuocere.\nCuoci il riso separatamente.\nServi il curry con il riso.',
  },
  {
    id: 6,
    title: 'Lasagne Vegetariane',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500',
    summary: 'Lasagne con verdure grigliate, besciamella e formaggio.',
    readyInMinutes: 60,
    servings: 6,
    healthScore: 75,
    vegetarian: true,
    extendedIngredients: [
      { id: 1, name: 'Pasta per lasagne', amount: 250, unit: 'g', original: '250g Pasta per lasagne' },
      { id: 2, name: 'Verdure grigliate', amount: 400, unit: 'g', original: '400g Verdure grigliate' },
      { id: 3, name: 'Besciamella', amount: 500, unit: 'ml', original: '500ml Besciamella' },
      { id: 4, name: 'Mozzarella', amount: 200, unit: 'g', original: '200g Mozzarella' },
    ],
    instructions: 'Prepara le verdure grigliate.\nPrepara la besciamella.\nStrati: pasta, verdure, besciamella, mozzarella.\nRipeti gli strati.\nInforna a 180°C per 40 minuti.',
  },
  {
    id: 7,
    title: 'Zuppa di Lenticchie',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
    summary: 'Zuppa calda e nutriente con lenticchie, carote e sedano.',
    readyInMinutes: 40,
    servings: 4,
    healthScore: 92,
    vegetarian: true,
    vegan: true,
    extendedIngredients: [
      { id: 1, name: 'Lenticchie', amount: 300, unit: 'g', original: '300g Lenticchie' },
      { id: 2, name: 'Carote', amount: 2, unit: 'pezzi', original: '2 Carote' },
      { id: 3, name: 'Sedano', amount: 2, unit: 'coste', original: '2 coste Sedano' },
      { id: 4, name: 'Brodo vegetale', amount: 1, unit: 'litro', original: '1 litro Brodo vegetale' },
    ],
    instructions: 'Lava le lenticchie.\nTaglia carote e sedano a cubetti.\nSoffriggi le verdure.\nAggiungi lenticchie e brodo.\nCuoci per 30 minuti fino a quando le lenticchie sono tenere.',
  },
  {
    id: 8,
    title: 'Pizza Margherita',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500',
    summary: 'Pizza classica con pomodoro, mozzarella e basilico fresco.',
    readyInMinutes: 20,
    servings: 2,
    healthScore: 70,
    vegetarian: true,
    extendedIngredients: [
      { id: 1, name: 'Impasto per pizza', amount: 300, unit: 'g', original: '300g Impasto' },
      { id: 2, name: 'Pomodoro', amount: 200, unit: 'g', original: '200g Pomodoro' },
      { id: 3, name: 'Mozzarella', amount: 200, unit: 'g', original: '200g Mozzarella' },
      { id: 4, name: 'Basilico', amount: 10, unit: 'foglie', original: '10 foglie Basilico' },
    ],
    instructions: 'Stendi l\'impasto su una teglia.\nSpalma il pomodoro.\nAggiungi la mozzarella a fette.\nInforna a 220°C per 15 minuti.\nAggiungi il basilico fresco prima di servire.',
  },
  {
    id: 9,
    title: 'Insalata di Riso',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500',
    summary: 'Insalata fresca con riso, verdure croccanti e condimento al limone.',
    readyInMinutes: 25,
    servings: 4,
    healthScore: 85,
    vegetarian: true,
    vegan: true,
    extendedIngredients: [
      { id: 1, name: 'Riso', amount: 300, unit: 'g', original: '300g Riso' },
      { id: 2, name: 'Peperoni', amount: 2, unit: 'pezzi', original: '2 Peperoni' },
      { id: 3, name: 'Zucchine', amount: 2, unit: 'pezzi', original: '2 Zucchine' },
      { id: 4, name: 'Limone', amount: 1, unit: 'pezzo', original: '1 Limone' },
    ],
    instructions: 'Cuoci il riso e lascialo raffreddare.\nTaglia peperoni e zucchine a cubetti.\nMescola riso e verdure.\nCondisci con olio, limone e sale.\nLascia riposare in frigorifero per 1 ora.',
  },
  {
    id: 10,
    title: 'Burger Vegetariano',
    image: 'https://images.unsplash.com/photo-1525059696034-4967a7290022?w=500',
    summary: 'Burger con fagioli, verdure e pane integrale.',
    readyInMinutes: 30,
    servings: 4,
    healthScore: 82,
    vegetarian: true,
    extendedIngredients: [
      { id: 1, name: 'Fagioli', amount: 400, unit: 'g', original: '400g Fagioli' },
      { id: 2, name: 'Pane integrale', amount: 4, unit: 'fette', original: '4 fette Pane' },
      { id: 3, name: 'Lattuga', amount: 4, unit: 'foglie', original: '4 foglie Lattuga' },
      { id: 4, name: 'Pomodoro', amount: 1, unit: 'pezzo', original: '1 Pomodoro' },
    ],
    instructions: 'Schiaccia i fagioli con una forchetta.\nAggiungi spezie e forma i burger.\nCuoci i burger in padella per 5 minuti per lato.\nScalda il pane.\nComponi il burger con lattuga e pomodoro.',
  },
];

export function getMockRecipeById(id: number): Recipe | null {
  return mockRecipes.find(r => r.id === id) || null;
}
